# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('baby_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('whats_up', models.CharField(blank=True, max_length=200, null=True)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babycare.Baby')),
            ],
        ),
    ]
