# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-14 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0002_iaer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iaer',
            new_name='Iaers',
        ),
    ]
